apiVersion: v1
kind: PersistentVolume
metadata:
  name: incoming-nfs-pv
  labels:
    app.kubernetes.io/part-of: capture-framework
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: synology.local
    path: /volume1/incoming
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
