apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: incoming-nfs-pvc
  namespace: capture
  labels:
    app.kubernetes.io/part-of: capture-framework
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: incoming-nfs-pv
