{{- if .Values.walhelmSource.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "recognizer.fullname" . }}-walhelm-fetch
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "recognizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: walhelm-fetch
{{- end }}
