{{- if .Values.documentScanner.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "recognizer.fullname" . }}-document-scanner
  namespace: {{ include "recognizer.hardwareNamespace" . }}
  labels:
    {{- include "recognizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: document-scanner
spec:
  selector:
    app.kubernetes.io/name: {{ include "recognizer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: document-scanner
  ports:
    - name: web-ui
      port: 8080
      targetPort: 8080
      protocol: TCP
{{- end }}
