apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: capture-workloads
  namespace: capture
  labels:
    app.kubernetes.io/part-of: capture-framework
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: capture-framework
  endpoints:
    - port: web-ui
      interval: 30s
      path: /metrics
    - port: http
      interval: 30s
      path: /metrics
