{{- if .Values.opticalRipper.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "recognizer.fullname" . }}-makemkv-license
  namespace: {{ include "recognizer.hardwareNamespace" . }}
  labels:
    {{- include "recognizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: optical-ripper
    app.kubernetes.io/part-of: recognizer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: makemkv-license
    creationPolicy: Owner
  data:
    - secretKey: license-key
      remoteRef:
        key: eso/recognizer/makemkv
        property: license-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "recognizer.fullname" . }}-omdb-api
  namespace: {{ include "recognizer.hardwareNamespace" . }}
  labels:
    {{- include "recognizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: optical-ripper
    app.kubernetes.io/part-of: recognizer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: omdb-api
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: eso/recognizer/omdb
        property: api-key
{{- end }}
