apiVersion: v1
kind: ConfigMap
metadata:
  name: arm-config
  namespace: capture
  labels:
    app.kubernetes.io/name: optical-ripper
    app.kubernetes.io/part-of: capture-framework
data:
  arm.yaml: |
    RIPMETHOD: "mkv"
    EJECTENABLED: true
    JUSTMAKEISO: false
    COMPLETED_PATH: "/out/video"
    AUDIO_COMPLETED_PATH: "/out/audio"
    DATA_COMPLETED_PATH: "/out/data"
    HANDBRAKE_PRESET: "disabled"
    NOTIFY_WEBHOOK: "http://notification-relay.capture.svc.cluster.local:8080/event"
