apiVersion: v1
kind: Service
metadata:
  name: optical-ripper
  namespace: capture
  labels:
    app.kubernetes.io/name: optical-ripper
    app.kubernetes.io/part-of: capture-framework
spec:
  selector:
    app.kubernetes.io/name: optical-ripper
  ports:
    - name: web-ui
      port: 8080
      targetPort: 8080
      protocol: TCP
